[hello_world]
icon = "👋"
name = "Hello, World!"
description = "Launch Terminal93 for the first time."

[chatterbox]
icon = "🗣️"
name = "Chatterbox"
description = "Send a live chat message."

[where_cookies]
icon = "🍪"
name = "Where are the cookies?"
description = "Click the counter button."

[unfunny_number]
icon = "🤨"
name = "Unfunny number"
description = "Click the button 67 times."

[funny_number]
icon = "🤣"
name = "Funny number"
description = "Click the button 69 times."

[warm_welcome]
icon = "🔗"
name = "A warm welcome"
description = "Click the secret link in the Welcome app."
secret = true

[magic_word]
icon = "🪄"
name = "What's the magic word?"
description = "Say \"please\" or \"thank you\" in the chat."
secret = true
