[project]
name = "terminal93"
version = "0.1.0"
description = "hug + hack = infinity"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "textual>=6.11.0",
]

[project.scripts]
terminal93 = "terminal93.__main__:main"

[dependency-groups]
dev = [
    "ruff>=0.14.10",
    "textual-dev>=1.8.0",
]

[tool.uv]
package = true

[tool.ruff.format]
quote-style = "single"
